#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-03-06 08:51:12.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("doRegroupings() works", {

  f <- kwb.prep:::doRegroupings

  expect_error(
    kwb.prep:::doRegroupings()
    # settings is not a list but:
#  NULL
  )

})
