#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-14 04:33:30.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("check_indices() works", {

  expect_error(
    kwb.prep:::check_indices()
    # Argument "indices" fehlt (ohne Standardwert)
  )

})

