#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-04 14:05:02.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_lower_extension() works", {

  f <- kwb.prep:::get_lower_extension
    
  expect_error(f())

})

