#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-14 04:32:39.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_file_metadata() works", {

  expect_error(
    kwb.prep:::get_file_metadata()
    # Argument "file" fehlt (ohne Standardwert)
  )

})

