#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-14 04:33:30.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("save_as_if() works", {

  expect_error(
    kwb.prep:::save_as_if()
    # Argument "do_save" fehlt (ohne Standardwert)
  )

})

