#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-14 04:33:30.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("indices_of_change() works", {

  expect_error(
    kwb.prep:::indices_of_change()
    # Argument "x" fehlt (ohne Standardwert)
  )

})

