#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-14 04:32:50.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("check_number_of_unique_if() works", {

  expect_error(
    kwb.prep:::check_number_of_unique_if()
    # Argument "check" fehlt (ohne Standardwert)
  )

})

