#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-04 14:04:47.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("read_config() works", {

  expect_error(
    kwb.prep:::read_config()
    # Argument "file_name" fehlt (ohne Standardwert)
  )

})

