#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-04 14:04:36.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("check_or_set_column_types_if() works", {

  f <- kwb.prep:::check_or_set_column_types_if

  df <- data.frame()

  expect_identical(f(df, FALSE), df)
})
