#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-04 14:04:51.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("contained_tables() works", {

  f <- kwb.prep::contained_tables

  expect_error(f())

  zip_file <- invalid_zip("five-rows.zip")

  expect_identical(f(zip_file, list(a = list(file = "a.txt"))), character(0))

  filename <- "DatenCO_Haltungen_utf8.csv"

  expect_identical(f(zip_file, list(a = list(file = filename))), "a")
})
