#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-14 04:32:37.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("delete_one_value_columns() works", {

  expect_error(
    kwb.prep:::delete_one_value_columns()
    # Argument "df" fehlt (ohne Standardwert)
  )

})

