#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-15 11:25:22.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("read_rename_select_csv() works", {

  f <- kwb.prep:::read_rename_select_csv
  
  expect_error(f())

})

