#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-15 11:25:16.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("check_table_name() works", {

  f <- kwb.prep:::check_table_name

  expect_error(f())

})
