#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-04 14:04:47.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("check_zip_extension() works", {

  f <- kwb.prep::check_zip_extension

  expect_error(f("a.txt"), "hat nicht die erwartete Dateiendung")
  expect_silent(f("a.zip"))
  expect_silent(f("a.7z"))
})
