#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-14 04:33:07.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("md_header() works", {

  expect_error(
    kwb.prep:::md_header()
    # No such list elements: 'key?'
# Available elements: 'applying_filter', 'applying_filter_to', 'by', 'calculating_new_columns', 'calculating_new_columns_in', 'column_x', 'column_y', 'columns_removed', 'columns_removed_reason', 'common_columns', 'creating_missing_column', 'deleting_constant_columns', 'hello', 'internal_field', 'key_columns', 'left_joining', 'left_table', 'merging', 'merging_failed', 'n_rows', 'name', 'new_line', 'no_columns_removed', 'no_duplicates', 'nrow_x', 'nrow_y', 'original_field', 'reading_args', 'reading_filter_criteria', 'removing_columns', 'removing_columns_from', 'renaming_columns', 'replacements_invalid_csv', 'result_table', 'right_table', 'select_columns', 'select_columns_from', 'select_rename_columns', 'select_rename_columns_from', 'structure_of', 'table', 'table_dimesion', 'table_name', 'type_x', 'type_y', 'unique_rows', 'writing_csv'
  )

})

