#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-14 04:32:37.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("find_identical_columns() works", {

  expect_error(
    kwb.prep:::find_identical_columns()
    # Argument "x" fehlt (ohne Standardwert)
  )

})

