#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-04 14:04:51.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("missing_tables() works", {

  f <- kwb.prep:::missing_tables

  #dir(invalid_zip())
  zip_file <- invalid_zip("two-tables-missing.zip")

  #kwb.prep:::get_zipped_paths(zip_file)

  expect_identical("a", f(zip_file, list(
    a = list(file = "abc.txt")
  )))

  expect_identical(character(0), f(zip_file, list(
    a = list(file = "DatenCO_Haltungen_utf8.csv")
  )))
})
