#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-14 04:33:12.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("rename_and_select() works", {

  expect_error(
    kwb.prep:::rename_and_select()
    # Argument "renamings" fehlt (ohne Standardwert)
  )

})

