#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-04 14:04:51.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("expected_tables() works", {

  f <- kwb.prep:::expected_tables

  expect_identical(f(list()), character(0))
  expect_identical(f(list(default = list())), character(0))

  expect_identical(f(list(a = list(file = "a.txt"))), "a")

  expect_identical(c("a", "b"), f(list(
    default = list(),
    a = list(file = "a.txt"),
    b = list(file = "b.txt")
  )))
})
