#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-14 04:32:50.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("replace_by_condition() works", {

  expect_error(
    kwb.prep:::replace_by_condition()
    # No such file: 'replace_invalid.csv' in
#   'C:/Users/hsonne/Documents/tmp/kwb.prep/config'.
# Available files:
#   ''
  )

})

