#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-03-06 08:51:11.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("breaksToIntervalLabels() works", {

  f <- kwb.prep:::breaksToIntervalLabels

  expect_error(
    kwb.prep:::breaksToIntervalLabels()
    # Argument "breaks" fehlt (ohne Standardwert)
  )

})
