#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-14 04:32:39.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("format.object_size() works", {

  expect_error(
    kwb.prep:::format.object_size()
    # Argument "x" fehlt (ohne Standardwert)
  )

})

