#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2021-02-14 04:33:21.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("unique_rows() works", {

  expect_error(
    kwb.prep:::unique_rows()
    # Argument "x" fehlt (ohne Standardwert)
  )

})

