applying_filter: Filterschritte '%s' anwenden
applying_filter_to: Filterschritte '%s' anwenden auf '%s'
by: verkn<ue>pft
calculating_new_columns: Berechnen neuer Spalten
calculating_new_columns_in: Berechnen neuer Spalten in '%s'
column: Spalte
column_name: Spaltenname
columns_removed: Die folgenden %d Spalten wurden aus '%s' entfernt:<nl><nl>%s<nl>
columns_removed_reason: Die folgenden %d Spalten wurden aus '%s' entfernt (%s):<nl><nl>%s<nl>
column_x: Spalte links
column_y: Spalte rechts
common_columns: The following columns are in '%s' as well as in '%s':<nl>- %s
condition: wenn
converting: Converting column '%s' from '%s' to '%s'
copying_csv_from_to: Kopieren der CSV-Dateien in<nl>  '%s'<nl>nach<nl>  '%s'
creating_missing_column: Creating missing column '%s'
current_type: aktueller Typ
data_type: Datentyp
deleting_constant_columns: Deleting 'constant' columns
duplicate_check: Duplikatpr<ue>fung
file: Datei
frequency: H<ae>ufigkeit
hello: sch<oe>ne Gr<ue>sse
import_dir_exists: Das Importverzeichnis existiert bereits:<nl>'%s'<nl>Es werden die darin
  enthaltenen Daten verwendet.
internal_field: Spaltenname intern
key_columns: Schl<ue>sselspalte(n)
left_joining: Tabellen verbinden (Left Join)
left_table: Linke Tabelle
loading_from_file_cache: Laden von '%s' aus dem Datei-Cache (.RData-Datei)
merging: 'Verbinden zweier Tabellen: ''%s'' x ''%s'''
merging_failed: Merging %s with %s led to %d more rows!
missing_fields_in_csv: |-
  Die folgenden Felder (Spalten) fehlen in den CSV-Dateien.
  Haben Sie die richtige CSV-Konfiguration ausgew<ae>hlt?

  %s
missing_tables: Die folgenden Tabellen (CSV-Dateien) fehlen:<nl>%s
modified: zuletzt ge<ae>ndert
most_frequent: h<ae>ufigste Werte
n_differences: There are %d differences between %s and %s!
n_distinct: distinkt
n_na: NA
n_replaced: Anzahl
n_rows: Anzahl Zeilen
name: Name
new_line: <nl>
nrow_x: Zeilen links
nrow_y: Zeilen rechts
no_columns_removed: Es wurden keine Spalten entfernt.
no_duplicates: 'Keine Duplikate in (Wertekombinationen der) Spalte(n): %s'
no_type_info_found: Keine Typinformation gefunden
not_in_file_cache: Ermitteln von '%s' (nicht im .RData-Datei-Cache gefunden)...
object_cached_in_file: Speichern von '%s' im Datei-Cache (.RData-Datei).
original_column: (umbenannt von)
original_field: Spaltenname original
read_csv_file: CSV-Datei einlesen
reading_args: 'Argumente f<ue>r Funktion %s() lesen aus: ''%s'''
reading_filter_criteria: Reading filter criteria from
removing_columns: Spalten entfernen
removing_columns_from: Spalten aus '%s' entfernen
renaming_columns: Spalten in '%s' umbenennen
replace_specials: Spezielle (ung<ue>ltige) Werte ersetzen
replacement: wird gesetzt auf
replacements_by_condition: Ersetzungen gem<ae><ss> replace-by-condition.csv, Gruppe
  '%s'
result_table: Ergebnistabelle
row_bind: Tabellen zeilenweise verbinden
right_table: Rechte Tabelle
select_columns: Spalten ausw<ae>hlen
select_columns_from: Spalten ausw<ae>hlen aus '%s'
select_rename_columns: Spalten ausw<ae>hlen (und umbenennen)
select_rename_columns_from: Spalten ausw<ae>hlen (und umbenennen) aus '%s'
selected_column: Ausgew<ae>hlt
size: Gr<oe><ss>e
structure_of: Struktur von '%s'
table: Tabelle
table_dimesion: Tabelle mit %d Zeilen und %d Spalten<nl>
table_name: Tabellenname
target: Spalte
type_x: Typ links
type_y: Typ rechts
unique_rows: Duplikatzeilen entfernen
unknown_columns_in_selection: |-
  Folgende Spalten der Auswahl '%s' (spezifiziert in '%s'), sind nicht im data frame enthalten, der an reorder_columns() <ue>bergeben wurde:
  %s
unzipping: Entzippen von<nl>  '%s'<nl>nach<nl>  '%s'
using_option_value: Using option value %s = '%s'
value: Wert
writing_csv: Schreiben von `%s`
