hello: sch<oe>ne Gr<ue>sse
key_columns: Schl<ue>sselspalte(n)
left_joining: Tabellen verbinden (Left Join)
left_table: Linke Tabelle
n_rows: Anzahl Zeilen
name: Name
new_line: <nl>
nrow_x: Zeilen links
nrow_y: Zeilen rechts
result_table: Ergebnistabelle
right_table: Rechte Tabelle
select_columns: Spalten ausw<ae>hlen
select_columns_from: Spalten ausw<ae>hlen aus '%s'
unique_rows: Duplikatzeilen entfernen
