applying_filter: Filterschritte '%s' anwenden
applying_filter_to: Filterschritte '%s' anwenden auf '%s'
by: verkn<ue>pft
calculating_new_columns: Berechnen neuer Spalten
calculating_new_columns_in: Berechnen neuer Spalten in '%s'
column: Spalte
columns_removed: Die folgenden %d Spalten wurden aus '%s' entfernt:<nl><nl>%s<nl>
columns_removed_reason: Die folgenden %d Spalten wurden aus '%s' entfernt (%s):<nl><nl>%s<nl>
column_x: Spalte links
column_y: Spalte rechts
common_columns: The following columns are in '%s' as well as in '%s':<nl>- %s
condition: wenn
creating_missing_column: Creating missing column '%s'
deleting_constant_columns: Deleting 'constant' columns
duplicate_check: Duplikatpr<ue>fung
file: Datei
frequency: H<ae>ufigkeit
hello: sch<oe>ne Gr<ue>sse
internal_field: Spaltenname intern
key_columns: Schl<ue>sselspalte(n)
left_joining: Tabellen verbinden (Left Join)
left_table: Linke Tabelle
loading_from_file_cache: Laden von '%s' aus dem Datei-Cache (.RData-Datei)
merging: 'Verbinden zweier Tabellen: ''%s'' x ''%s'''
merging_failed: Merging %s with %s led to %d more rows!
modified: zuletzt ge<ae>ndert
n_differences: There are %d differences between %s and %s!
n_replaced: Anzahl
n_rows: Anzahl Zeilen
name: Name
new_line: <nl>
nrow_x: Zeilen links
nrow_y: Zeilen rechts
no_columns_removed: Es wurden keine Spalten entfernt.
no_duplicates: 'Keine Duplikate in (Wertekombinationen der) Spalte(n): %s'
not_in_file_cache: Objekt '%s' ist noch nicht im Datei-Cache (.RData-Datei) vorhanden
  und wird nun eingelesen/berechnet.
object_cached_in_file: Speichern von '%s' im Datei-Cache (.RData-Datei).
original_column: (umbenannt von)
original_field: Spaltenname original
read_csv_file: CSV-Datei einlesen
reading_args: 'Argumente f<ue>r Funktion %s() lesen aus: ''%s'''
reading_filter_criteria: Reading filter criteria from
removing_columns: Spalten entfernen
removing_columns_from: Spalten aus '%s' entfernen
renaming_columns: Spalten in '%s' umbenennen:<nl>
replace_specials: Spezielle (ung<ue>ltige) Werte ersetzen
replacement: wird gesetzt auf
replacements_invalid_csv: Ersetzungen gem<ae><ss> replace_invalid.csv, Gruppe '%s'
result_table: Ergebnistabelle
row_bind: Tabellen zeilenweise verbinden
right_table: Rechte Tabelle
select_columns: Spalten ausw<ae>hlen
select_columns_from: Spalten ausw<ae>hlen aus '%s'
select_rename_columns: Spalten ausw<ae>hlen (und umbenennen)
select_rename_columns_from: Spalten ausw<ae>hlen (und umbenennen) aus '%s'
selected_column: Ausgew<ae>hlt
size: Gr<oe><ss>e
structure_of: Struktur von '%s'
table: Tabelle
table_dimesion: Tabelle mit %d Zeilen und %d Spalten<nl>
table_name: Tabellenname
target_column: Spalte
type_x: Typ links
type_y: Typ rechts
unique_rows: Duplikatzeilen entfernen
using_option_value: Using option value %s = '%s'
value: Wert
writing_csv: Schreiben von `%s`
